AWSTemplateFormatVersion: 2010-09-09
Resources:
    PuppetMaster1:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t2.small
            ImageId: ami-062f7200baf2fa504
            KeyName: puppet
            Monitoring: true
            Tags:
                - Key: Name
                  Value: puppet-master-1
            NetworkInterfaces:
                - AssociatePublicIpAddress: true
                  DeviceIndex: 0
                  GroupSet:
                    - !ImportValue puppet-sg-id
                  SubnetId: !ImportValue myvpc-public-subnet-1
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash -xe
                    rpm -ivh https://yum.puppet.com/puppet6/puppet-release-el-7.noarch.rpm
                    yum install -y puppetserver
                    sed -i 's/-Xms2g -Xmx2g/-Xms512m -Xmx512m/g' /etc/sysconfig/puppetserver
                    sudo -- sh -c 'echo -en $"\n[main]\nserver = `hostname`" >> /etc/puppetlabs/puppet/puppet.conf'
                    rm -fr /etc/puppetlabs/puppet/ssl
                    /opt/puppetlabs/bin/puppetserver ca setup
                    systemctl enable puppetserver
                    yum update -y
                    reboot
